# Azure Key Vault Secret Store Component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-keyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: "{KEY_VAULT_NAME}" # Replace with actual Key Vault name
    - name: azureClientId
      value: "" # Leave empty for Managed Identity


